jobs:
  - job: 'Build'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core 3.x'
      inputs:
        version: '3.x'
    
    - pwsh: ./build.ps1 --target=ContinuousIntegration
      displayName: 'Build with Cake'
      env:
        GITHUB_USERNAME: $(GITHUB_USERNAME)
        GITHUB_TOKEN: $(GITHUB_TOKEN)